name: Elements of Eden
favicon: null
layout_spectrum: 0.99521
typography_spectrum: 0.30743
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b3be9e'
    - '#b2c3d7'
    - '#d6dee9'
    - '#a8bad2'
    - '#bdcadb'
  brandStrength: 0.625
  lightness: 0.3125
  saturation: 0.875
  rhythmicContrast: 0.75
purpose: []
