name: Elements of Eden
favicon: null
layout_spectrum: 0.4096670572180301
typography_spectrum: 0.8248401014134288
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.21639974135905504
  lightness: 0.23104658303782344
  saturation: 0.7322945410851389
  rhythmicContrast: 0.09992725076153874
purpose: []
