name: Elements of Eden
favicon: null
layout_spectrum: 0.4096670572180301
typography_spectrum: 0.30743
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b3be9e'
    - '#b2c3d7'
    - '#d6dee9'
    - '#a8bad2'
    - '#bdcadb'
  brandStrength: 0.375
  lightness: 0.1875
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
