name: Elements of Eden
favicon: null
layout_spectrum: 0.51
typography_spectrum: 0.8248401014134288
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#11100c'
    - '#646458'
    - '#aea177'
    - '#94dc8e'
  brandStrength: 0.25
  lightness: 0.375
  saturation: 0.9375
  rhythmicContrast: 0.25
purpose: []
